### ISSUE TITLE
Issues with compiling

### ISSUE THREAD

**Issue by Lavvii** [ArcyDev/Vs-Retrospecter#1]
When I try to compile I get left with this 

source/FreeplayState.hx:682: characters 68-69 : Missing ;
source/FreeplayState.hx:688: characters 80-81 : Missing ;
source/FreeplayState.hx:542: characters 68-69 : Missing ;
source/FreeplayState.hx:548: characters 80-81 : Missing ;

I'm on macOs

**Comment by perngjiafu** [comment]
it also doesnt work on windows

**Comment by perngjiafu** [comment]
ok i got it uhm there is "//" on each lines. delete them.

eg. line 552 ---> 		else
		{
	//diffCalcText.text = 'RATING: ${DiffCalc.CalculateDiff(songData.get(songs[curSelected].songName)[curDifficulty])}';
		diffCalcText.text = 'RATING: ${difficultyRatings[curSelected][curDifficulty])}';
		diffText.text = CoolUtil.difficultyFromInt(curDifficulty).toUpperCase();
		}
		
		
replace to 		else
		{
	diffCalcText.text = 'RATING: ${DiffCalc.CalculateDiff(songData.get(songs[curSelected].songName)[curDifficulty])}';
	//diffCalcText.text = 'RATING: ${difficultyRatings[curSelected][curDifficulty])}';
	diffText.text = CoolUtil.difficultyFromInt(curDifficulty).toUpperCase();
		}

**Comment by perngjiafu** [comment]
if you replace them in line 682, 688, 542 and 548 it should run up the game

**Comment by gummybear17** [comment]
just delete this ) it will build the game on thoese written code

**Comment by CarbonatedChicken** [comment]
Fixed
