### ISSUE TITLE
i can't complie 

### ISSUE THREAD

**Issue by Jonnycatmeow** [ArcyDev/Vs-Retrospecter#2]
source/FreeplayState.hx:682: characters 68-69 : Missing ;
source/FreeplayState.hx:688: characters 80-81 : Missing ;
source/FreeplayState.hx:542: characters 68-69 : Missing ;
source/FreeplayState.hx:548: characters 80-81 : Missing ; 
these are the problems please fix it 
and im on mac

**Comment by CarbonatedChicken** [comment]
Duplicate + Fixed
