### ISSUE TITLE
Game moving on its own

### ISSUE THREAD

**Issue by FuroYT** [ArcyDev/Vs-Retrospecter#7]
## Description
What's happening? Add a brief description of what the bug is, attaching screenshots helps!

The sway effect in satisfracture/modchart.lua is glitched my game windows is literally moving by its own

## Computer Specs
- What OS is your computer running? (Windows 7, Windows 8, Windows 10, Windows 11, Mac OS, Linux)
Windows 11
- Graphics Card: Nvdia GeForce GTX 1660
- Installed RAM: 8 gb 

(Can't get the save file cause I can't go to GitHub on my pc lmao it's doesn't want to let me the access)

**Comment by FuroYT** [comment]
And I can rebuild the game just tell me the hx file where the sway effect code is

**Comment by spider211046affffhghgcxcxcxcxcx** [comment]
nicce
